# Auto-generated column configuration using TIKR /tf metadata.
statements =[
    {
        "statement": "income_statement",
        "keys": {
            "revenues": "Revenues",
            "total_revenues": "Total Revenues",
            "total_revenues_yoy": "% Change YoY",
            "cost_of_goods_sold": "Cost of Goods Sold",
            "gross_profit": "Gross Profit",
            "gross_profit_yoy": "% Change YoY",
            "gross_profit_margin": "% Gross Margins",
            "selling_general_admin_expenses": "Selling General & Admin Expenses",
            "rd_expenses": "R&D Expenses",
            "total_operating_expenses": "Total Operating Expenses",
            "operating_income": "Operating Income",
            "operating_income_yoy": "% Change YoY",
            "operating_margin": "% Operating Margins",
            "interest_expense": "Interest Expense",
            "interest_and_investment_income": "Interest And Investment Income",
            "currency_exchange_gains_loss": "Currency Exchange Gains (Loss)",
            "other_non_operating_income_expenses": "Other Non Operating Income (Expenses)",
            "ebt_excl_unusual_items": "EBT Excl. Unusual Items",
            "merger_restructuring_charges": "Merger & Restructuring Charges",
            "gain_loss_on_sale_of_investments": "Gain (Loss) On Sale Of Investments",
            "gain_loss_on_sale_of_assets": "Gain (Loss) on Sale of Assets (Rev)",
            "asset_writedown": "Asset Writedown & Restructuring Costs",
            "in_process_rd_expenses": "In Process R&D Expenses",
            "legal_settlements": "Legal Settlements",
            "other_unusual_items": "Other Unusual Items",
            "ebt_incl_unusual_items": "EBT Incl. Unusual Items",
            "income_tax_expense": "Income Tax Expense",
            "earnings_from_continuing_operations": "Earnings From Continuing Operations",
            "earnings_of_discontinued_operations": "Earnings Of Discontinued Operations",
            "extraordinary_item_accounting_change": "Extraordinary Item & Accounting Change",
            "net_income_to_company": "Net Income to Company",
            "net_income": "Net Income",
            "net_income_to_common_incl_extra_items": "Net Income to Common Incl Extra Items",
            "net_income_to_common_incl_extra_items_margins": "% Net Income to Common Incl Extra Items Margins",
            "net_income_to_common_excl_extra_items": "Net Income to Common Excl. Extra Items",
            "net_income_to_common_excl_extra_items_margins": "% Net Income to Common Excl. Extra Items Margins",
            "diluted_eps_excl_extra_items": "Diluted EPS Excl Extra Items",
            "diluted_eps_excl_extra_items_yoy": "% Change YoY",
            "weighted_average_diluted_shares_outstanding": "Weighted Average Diluted Shares Outstanding",
            "weighted_average_diluted_shares_outstanding_yoy": "% Change YoY",
            "weighted_average_basic_shares_outstanding": "Weighted Average Basic Shares Outstanding",
            "weighted_average_basic_shares_outstanding_yoy": "% Change YoY",
            "dividends_per_share": "Dividends Per Share",
            "dividends_per_share_yoy": "% Change YoY",
            "payout_ratio": "Payout Ratio %",
            "basic_eps": "Basic EPS",
            "ebitda": "EBITDA",
            "ebitda_yoy": "% Change YoY",
            "ebitdar": "EBITDAR",
            "rd_expense": "R&D Expense",
            "selling_and_marketing_expense": "Selling and Marketing Expense",
            "general_and_administrative_expense": "General and Administrative Expense",
            "effective_tax_rate": "Effective Tax Rate %"
        }
    },
    {
        "statement": "cashflow_statement",
        "keys": {
            "net_income": "Net Income",
            "depreciation_amortization": "Depreciation & Amortization",
            "amortization_of_goodwill_and_intangible_assets": "Amortization of Goodwill and Intangible Assets",
            "amortization_of_deferred_charges": "Amortization of Deferred Charges",
            "total_depreciation_amortization": "Total Depreciation & Amortization",
            "gain_loss_from_sale_of_asset": "(Gain) Loss From Sale Of Asset",
            "gain_loss_on_sale_of_investments": "(Gain) Loss on Sale of Investments",
            "asset_writedown_restructuring_costs": "Asset Writedown & Restructuring Costs",
            "stock_based_compensation": "Stock-Based Compensation",
            "tax_benefit_from_stock_options": "Tax Benefit from Stock Options",
            "net_cash_from_discontinued_operations": "Net Cash From Discontinued Operations",
            "other_operating_activities": "Other Operating Activities",
            "change_in_accounts_receivable": "Change In Accounts Receivable",
            "change_in_inventories": "Change In Inventories",
            "change_in_accounts_payable": "Change In Accounts Payable",
            "change_in_unearned_revenues": "Change in Unearned Revenues",
            "change_in_income_taxes": "Change In Income Taxes",
            "change_in_other_net_operating_assets": "Change in Other Net Operating Assets",
            "cash_from_operations": "Cash from Operations",
            "change_in_net_working_capital": "Memo: Change in Net Working Capital",
            "capital_expenditure": "Capital Expenditure",
            "sale_of_property_plant_and_equipment": "Sale of Property, Plant, and Equipment",
            "cash_acquisitions": "Cash Acquisitions",
            "divestitures": "Divestitures",
            "sale_of_intangible_assets": "Sale (Purchase) of Intangible assets",
            "investment_in_marketable_and_equity_securities": "Investment in Marketable and Equity Securities",
            "other_investing_activities": "Other Investing Activities",
            "cash_from_investing": "Cash from Investing",
            "total_debt_issued": "Total Debt Issued",
            "total_debt_repaid": "Total Debt Repaid",
            "issuance_of_common_stock": "Issuance of Common Stock",
            "repurchase_of_common_stock": "Repurchase of Common Stock",
            "common_dividends_paid": "Common Dividends Paid",
            "common_preferred_stock_dividends_paid": "Common & Preferred Stock Dividends Paid",
            "other_financing_activities": "Other Financing Activities",
            "cash_from_financing": "Cash from Financing",
            "foreign_exchange_rate_adjustments": "Foreign Exchange Rate Adjustments",
            "net_change_in_cash": "Net Change in Cash",
            "free_cash_flow": "Free Cash Flow",
            "free_cash_flow_yoy": "% Change YoY",
            "free_cash_flow_margins": "% Free Cash Flow Margins",
            "cash_and_cash_equivalents_beginning_of_period": "Cash and Cash Equivalents, Beginning of Period",
            "cash_and_cash_equivalents_end_of_period": "Cash and Cash Equivalents, End of Period",
            "cash_interest_paid": "Cash Interest Paid",
            "cash_taxes_paid": "Cash Taxes Paid",
            "cash_flow_per_share": "Cash Flow per Share"
        }
    },
    {
        "statement": "balancesheet_statement",
        "keys": {
            "cash_and_equivalents": "Cash And Equivalents",
            "short_term_investments": "Short Term Investments",
            "trading_asset_securities": "Trading Asset Securities",
            "total_cash_and_short_term_investments": "Total Cash And Short Term Investments",
            "accounts_receivable": "Accounts Receivable",
            "other_receivables": "Other Receivables",
            "notes_receivable": "Notes Receivable",
            "total_receivables": "Total Receivables",
            "inventory": "Inventory",
            "prepaid_expenses": "Prepaid Expenses",
            "deferred_tax_assets_current": "Deferred Tax Assets Current",
            "restricted_cash": "Restricted Cash",
            "other_current_assets": "Other Current Assets",
            "total_current_assets": "Total Current Assets",
            "gross_property_plant_and_equipment": "Gross Property Plant And Equipment",
            "accumulated_depreciation": "Accumulated Depreciation",
            "net_property_plant_and_equipment": "Net Property Plant And Equipment",
            "long_term_investments": "Long-term Investments",
            "goodwill": "Goodwill",
            "other_intangibles": "Other Intangibles",
            "loans_receivable_long_term": "Loans Receivable Long-Term",
            "deferred_tax_assets_long_term": "Deferred Tax Assets Long-Term",
            "other_long_term_assets": "Other Long-Term Assets",
            "total_assets": "Total Assets",
            "accounts_payable": "Accounts Payable",
            "accrued_expenses": "Accrued Expenses",
            "short_term_borrowings": "Short-term Borrowings",
            "current_portion_of_long_term_debt": "Current Portion of Long-Term Debt",
            "current_portion_of_capital_lease_obligations": "Current Portion of Capital Lease Obligations",
            "current_income_taxes_payable": "Current Income Taxes Payable",
            "unearned_revenue_current": "Unearned Revenue Current",
            "other_current_liabilities": "Other Current Liabilities",
            "total_current_liabilities": "Total Current Liabilities",
            "long_term_debt": "Long-Term Debt",
            "capital_leases": "Capital Leases",
            "unearned_revenue_non_current": "Unearned Revenue Non Current",
            "deferred_tax_liability_non_current": "Deferred Tax Liability Non Current",
            "other_non_current_liabilities": "Other Non Current Liabilities",
            "total_liabilities": "Total Liabilities",
            "preferred_stock_redeemable": "Preferred Stock Redeemable",
            "preferred_stock_non_redeemable": "Preferred Stock Non Redeemable",
            "preferred_stock_convertible": "Preferred Stock Convertible",
            "preferred_stock_others": "Preferred Stock - Others",
            "total_preferred_equity": "Total Preferred Equity",
            "common_stock": "Common Stock",
            "additional_paid_in_capital": "Additional Paid In Capital",
            "retained_earnings": "Retained Earnings",
            "comprehensive_income_and_other": "Comprehensive Income and Other",
            "total_common_equity": "Total Common Equity",
            "total_equity": "Total Equity",
            "total_liabilities_and_equity": "Total Liabilities And Equity",
            "total_shares_out_on_filing_date": "Total Shares Out. on Filing Date",
            "book_value_share": "Book Value / Share",
            "tangible_book_value": "Tangible Book Value",
            "tangible_book_value_share": "Tangible Book Value / Share",
            "total_debt": "Total Debt",
            "net_debt": "Net Debt",
            "total_minority_interest": "Total Minority Interest",
            "equity_method_investments": "Equity Method Investments",
            "land": "Land",
            "buildings": "Buildings",
            "construction_in_progress": "Construction In Progress",
            "full_time_employees": "Full Time Employees"
        }
    },
    {
        "statement": "multiples_statement",
        "keys": {
            "ntm_total_enterprise_value_revenues": "NTM Total Enterprise Value / Revenues",
            "ntm_price_sales_ps": "NTM Price / Sales (P/S)",
            "ntm_total_enterprise_value_gross_profit": "NTM Total Enterprise Value / Gross Profit",
            "ntm_total_enterprise_value_ebitda": "NTM Total Enterprise Value / EBITDA",
            "ntm_total_enterprise_value_ebit": "NTM Total Enterprise Value / EBIT",
            "ntm_price_normalized_earnings_pe": "NTM Price / Normalized Earnings (P/E)",
            "peg_ratio": "PEG Ratio",
            "ntm_market_cap_free_cash_flow": "NTM Market Cap / Free Cash Flow",
            "ntm_levered_free_cash_flow_yield": "NTM Levered Free Cash Flow Yield",
            "ntm_price_ffo_per_share": "NTM Price / FFO Per Share",
            "ntm_price_affo_per_share": "NTM Price / AFFO Per Share",
            "ntm_dividend_yield": "NTM Dividend Yield",
            "ltm_total_enterprise_value_revenues": "LTM Total Enterprise Value / Revenues",
            "ltm_price_sales_ps": "LTM Price / Sales (P/S)",
            "ltm_total_enterprise_value_gross_profit": "LTM Total Enterprise Value / Gross Profit",
            "ltm_total_enterprise_value_ebitda": "LTM Total Enterprise Value / EBITDA",
            "ltm_total_enterprise_value_ebit": "LTM Total Enterprise Value / EBIT",
            "ltm_price_diluted_eps_pe": "LTM Price / Diluted EPS (P/E)",
            "ltm_price_book_value_per_share": "LTM Price / Book Value per Share",
            "ltm_price_tangible_book_value_per_share": "LTM Price / Tangible Book Value per Share",
            "ltm_total_enterprise_value_unlevered_free_cash_flow": "LTM Total Enterprise Value / Unlevered Free Cash Flow",
            "ltm_market_cap_levered_free_cash_flow": "LTM Market Cap / Levered Free Cash Flow",
            "ltm_price_net_current_asset_value": "LTM Price / Net Current Asset Value",
            "ltm_dividend_yield": "LTM Dividend Yield",
            "price": "Price",
            "total_enterprise_value_mm": "Total Enterprise Value (MM)",
            "market_cap_mm": "Market Cap (MM)",
            "ntm_gross_profit": "NTM Gross Profit",
            "ntm_revenues": "NTM Revenues",
            "ntm_ebitda": "NTM EBITDA",
            "ntm_ebit": "NTM EBIT",
            "ntm_normalized_earnings_per_share": "NTM Normalized Earnings Per Share",
            "ntm_normalized_eps_yoy_growth": "NTM Normalized EPS YoY Growth",
            "ntm_normalized_pe_multiple": "NTM Normalized PE Multiple",
            "ntm_gaap_earnings": "NTM GAAP Earnings",
            "ntm_dividend_share": "NTM Dividend / Share",
            "ntm_levered_free_cash_flow": "NTM Levered Free Cash Flow",
            "ntm_distributable_cash_per_share": "NTM Distributable Cash Per Share",
            "ntm_ffo_per_share": "NTM FFO Per Share",
            "ntm_affo_per_share": "NTM AFFO Per Share",
            "ntm_bv_per_share": "NTM BV Per Share",
            "ntm_nav_per_share": "NTM NAV Per Share",
            "ltm_revenues": "LTM Revenues",
            "ltm_gross_profit": "LTM Gross Profit",
            "ltm_ebitda": "LTM EBITDA",
            "ltm_ebit": "LTM EBIT",
            "ltm_diluted_eps_before_extra": "LTM Diluted EPS Before Extra",
            "ltm_book_value_per_share": "LTM Book Value per Share",
            "ltm_tangible_book_value_per_share": "LTM Tangible Book Value per Share",
            "ltm_dividend_per_share": "LTM Dividend Per Share",
            "ltm_unlevered_free_cash_flow": "LTM Unlevered Free Cash Flow",
            "ltm_levered_free_cash_flow": "LTM Levered Free Cash Flow",
            "ltm_net_current_asset_value_per_share": "LTM Net Current Asset Value Per Share"
        }
    }
]