-- Creación de la base de datos unificada
CREATE DATABASE IF NOT EXISTS investing_db
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE investing_db;

-- 1. Tabla: income_statement
CREATE TABLE IF NOT EXISTS income_statement (
    company VARCHAR(255) NOT NULL,
    year INT NOT NULL,
    revenues DOUBLE,
    total_revenues DOUBLE,
    total_revenues_yoy DOUBLE,
    cost_of_goods_sold DOUBLE,
    gross_profit DOUBLE,
    gross_profit_yoy DOUBLE,
    gross_profit_margin DOUBLE,
    selling_general_admin_expenses DOUBLE,
    rd_expenses DOUBLE,
    total_operating_expenses DOUBLE,
    operating_income DOUBLE,
    operating_income_yoy DOUBLE,
    operating_margin DOUBLE,
    interest_expense DOUBLE,
    interest_and_investment_income DOUBLE,
    currency_exchange_gains_loss DOUBLE,
    other_non_operating_income_expenses DOUBLE,
    ebt_excl_unusual_items DOUBLE,
    merger_restructuring_charges DOUBLE,
    gain_loss_on_sale_of_investments DOUBLE,
    gain_loss_on_sale_of_assets DOUBLE,
    asset_writedown DOUBLE,
    in_process_rd_expenses DOUBLE,
    legal_settlements DOUBLE,
    other_unusual_items DOUBLE,
    ebt_incl_unusual_items DOUBLE,
    income_tax_expense DOUBLE,
    earnings_from_continuing_operations DOUBLE,
    earnings_of_discontinued_operations DOUBLE,
    extraordinary_item_accounting_change DOUBLE,
    net_income_to_company DOUBLE,
    net_income DOUBLE,
    net_income_to_common_incl_extra_items DOUBLE,
    net_income_to_common_incl_extra_items_margins DOUBLE,
    net_income_to_common_excl_extra_items DOUBLE,
    net_income_to_common_excl_extra_items_margins DOUBLE,
    diluted_eps_excl_extra_items DOUBLE,
    diluted_eps_excl_extra_items_yoy DOUBLE,
    weighted_average_diluted_shares_outstanding DOUBLE,
    weighted_average_diluted_shares_outstanding_yoy DOUBLE,
    weighted_average_basic_shares_outstanding DOUBLE,
    weighted_average_basic_shares_outstanding_yoy DOUBLE,
    dividends_per_share DOUBLE,
    dividends_per_share_yoy DOUBLE,
    payout_ratio DOUBLE,
    basic_eps DOUBLE,
    ebitda DOUBLE,
    ebitda_yoy DOUBLE,
    ebitdar DOUBLE,
    rd_expense DOUBLE,
    selling_and_marketing_expense DOUBLE,
    general_and_administrative_expense DOUBLE,
    effective_tax_rate DOUBLE,
    market_cap DOUBLE,
    price_close DOUBLE,
    TEV DOUBLE,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (company, year)
);

-- 2. Tabla: cashflow_statement
CREATE TABLE IF NOT EXISTS cashflow_statement (
    company VARCHAR(255) NOT NULL,
    year INT NOT NULL,
    net_income DOUBLE,
    depreciation_amortization DOUBLE,
    amortization_of_goodwill_and_intangible_assets DOUBLE,
    amortization_of_deferred_charges DOUBLE,
    total_depreciation_amortization DOUBLE,
    gain_loss_from_sale_of_asset DOUBLE,
    gain_loss_on_sale_of_investments DOUBLE,
    asset_writedown_restructuring_costs DOUBLE,
    stock_based_compensation DOUBLE,
    tax_benefit_from_stock_options DOUBLE,
    net_cash_from_discontinued_operations DOUBLE,
    other_operating_activities DOUBLE,
    change_in_accounts_receivable DOUBLE,
    change_in_inventories DOUBLE,
    change_in_accounts_payable DOUBLE,
    change_in_unearned_revenues DOUBLE,
    change_in_income_taxes DOUBLE,
    change_in_other_net_operating_assets DOUBLE,
    cash_from_operations DOUBLE,
    change_in_net_working_capital DOUBLE,
    capital_expenditure DOUBLE,
    sale_of_property_plant_and_equipment DOUBLE,
    cash_acquisitions DOUBLE,
    divestitures DOUBLE,
    sale_of_intangible_assets DOUBLE,
    investment_in_marketable_and_equity_securities DOUBLE,
    other_investing_activities DOUBLE,
    cash_from_investing DOUBLE,
    total_debt_issued DOUBLE,
    total_debt_repaid DOUBLE,
    issuance_of_common_stock DOUBLE,
    repurchase_of_common_stock DOUBLE,
    common_dividends_paid DOUBLE,
    common_preferred_stock_dividends_paid DOUBLE,
    other_financing_activities DOUBLE,
    cash_from_financing DOUBLE,
    foreign_exchange_rate_adjustments DOUBLE,
    net_change_in_cash DOUBLE,
    free_cash_flow DOUBLE,
    free_cash_flow_yoy DOUBLE,
    free_cash_flow_margins DOUBLE,
    cash_and_cash_equivalents_beginning_of_period DOUBLE,
    cash_and_cash_equivalents_end_of_period DOUBLE,
    cash_interest_paid DOUBLE,
    cash_taxes_paid DOUBLE,
    cash_flow_per_share DOUBLE,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (company, year)
);

-- 3. Tabla: balancesheet_statement
CREATE TABLE IF NOT EXISTS balancesheet_statement (
    company VARCHAR(255) NOT NULL,
    year INT NOT NULL,
    cash_and_equivalents DOUBLE,
    short_term_investments DOUBLE,
    trading_asset_securities DOUBLE,
    total_cash_and_short_term_investments DOUBLE,
    accounts_receivable DOUBLE,
    other_receivables DOUBLE,
    notes_receivable DOUBLE,
    total_receivables DOUBLE,
    inventory DOUBLE,
    prepaid_expenses DOUBLE,
    deferred_tax_assets_current DOUBLE,
    restricted_cash DOUBLE,
    other_current_assets DOUBLE,
    total_current_assets DOUBLE,
    gross_property_plant_and_equipment DOUBLE,
    accumulated_depreciation DOUBLE,
    net_property_plant_and_equipment DOUBLE,
    long_term_investments DOUBLE,
    goodwill DOUBLE,
    other_intangibles DOUBLE,
    loans_receivable_long_term DOUBLE,
    deferred_tax_assets_long_term DOUBLE,
    other_long_term_assets DOUBLE,
    total_assets DOUBLE,
    accounts_payable DOUBLE,
    accrued_expenses DOUBLE,
    short_term_borrowings DOUBLE,
    current_portion_of_long_term_debt DOUBLE,
    current_portion_of_capital_lease_obligations DOUBLE,
    current_income_taxes_payable DOUBLE,
    unearned_revenue_current DOUBLE,
    other_current_liabilities DOUBLE,
    total_current_liabilities DOUBLE,
    long_term_debt DOUBLE,
    capital_leases DOUBLE,
    unearned_revenue_non_current DOUBLE,
    deferred_tax_liability_non_current DOUBLE,
    other_non_current_liabilities DOUBLE,
    total_liabilities DOUBLE,
    preferred_stock_redeemable DOUBLE,
    preferred_stock_non_redeemable DOUBLE,
    preferred_stock_convertible DOUBLE,
    preferred_stock_others DOUBLE,
    total_preferred_equity DOUBLE,
    common_stock DOUBLE,
    additional_paid_in_capital DOUBLE,
    retained_earnings DOUBLE,
    comprehensive_income_and_other DOUBLE,
    total_common_equity DOUBLE,
    total_equity DOUBLE,
    total_liabilities_and_equity DOUBLE,
    total_shares_out_on_filing_date DOUBLE,
    book_value_share DOUBLE,
    tangible_book_value DOUBLE,
    tangible_book_value_share DOUBLE,
    total_debt DOUBLE,
    net_debt DOUBLE,
    total_minority_interest DOUBLE,
    equity_method_investments DOUBLE,
    land DOUBLE,
    buildings DOUBLE,
    construction_in_progress DOUBLE,
    full_time_employees DOUBLE,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (company, year)
);

-- 4. Tabla: multiples_statement
CREATE TABLE IF NOT EXISTS multiples_statement (
    company VARCHAR(255) NOT NULL,
    year INT NOT NULL,
    ntm_total_enterprise_value_revenues DOUBLE,
    ntm_price_sales_ps DOUBLE,
    ntm_total_enterprise_value_gross_profit DOUBLE,
    ntm_total_enterprise_value_ebitda DOUBLE,
    ntm_total_enterprise_value_ebit DOUBLE,
    ntm_price_normalized_earnings_pe DOUBLE,
    peg_ratio DOUBLE,
    ntm_market_cap_free_cash_flow DOUBLE,
    ntm_levered_free_cash_flow_yield DOUBLE,
    ntm_price_ffo_per_share DOUBLE,
    ntm_price_affo_per_share DOUBLE,
    ntm_dividend_yield DOUBLE,
    trailing_multiples DOUBLE,
    ltm_total_enterprise_value_revenues DOUBLE,
    ltm_price_sales_ps DOUBLE,
    ltm_total_enterprise_value_gross_profit DOUBLE,
    ltm_total_enterprise_value_ebitda DOUBLE,
    ltm_total_enterprise_value_ebit DOUBLE,
    ltm_price_diluted_eps_pe DOUBLE,
    ltm_price_book_value_per_share DOUBLE,
    ltm_price_tangible_book_value_per_share DOUBLE,
    ltm_total_enterprise_value_unlevered_free_cash_flow DOUBLE,
    ltm_market_cap_levered_free_cash_flow DOUBLE,
    ltm_price_net_current_asset_value DOUBLE,
    ltm_dividend_yield DOUBLE,
    price_factors DOUBLE,
    price DOUBLE,
    total_enterprise_value_mm DOUBLE,
    market_cap_mm DOUBLE,
    forward_factors DOUBLE,
    ntm_gross_profit DOUBLE,
    ntm_revenues DOUBLE,
    ntm_ebitda DOUBLE,
    ntm_ebit DOUBLE,
    ntm_normalized_earnings_per_share DOUBLE,
    ntm_normalized_eps_yoy_growth DOUBLE,
    ntm_normalized_pe_multiple DOUBLE,
    ntm_gaap_earnings DOUBLE,
    ntm_dividend_share DOUBLE,
    ntm_levered_free_cash_flow DOUBLE,
    ntm_distributable_cash_per_share DOUBLE,
    ntm_ffo_per_share DOUBLE,
    ntm_affo_per_share DOUBLE,
    ntm_bv_per_share DOUBLE,
    ntm_nav_per_share DOUBLE,
    trailing_factors DOUBLE,
    ltm_revenues DOUBLE,
    ltm_gross_profit DOUBLE,
    ltm_ebitda DOUBLE,
    ltm_ebit DOUBLE,
    ltm_diluted_eps_before_extra DOUBLE,
    ltm_book_value_per_share DOUBLE,
    ltm_tangible_book_value_per_share DOUBLE,
    ltm_dividend_per_share DOUBLE,
    ltm_unlevered_free_cash_flow DOUBLE,
    ltm_levered_free_cash_flow DOUBLE,
    ltm_net_current_asset_value_per_share DOUBLE,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (company, year)
);

-- 5. Tabla: approved_users
CREATE TABLE IF NOT EXISTS approved_users (
    user_name VARCHAR(255) PRIMARY KEY,
    active TINYINT DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    blocked_at DATETIME NULL,
    released_at DATETIME NULL
);

-- 6. Tabla: users_block_history
CREATE TABLE IF NOT EXISTS user_block_history (
    user_name VARCHAR(255) NOT NULL,
    blocked_at DATETIME NULL,
    released_at DATETIME NULL
);

-- 6. Tabla: users_log
CREATE TABLE IF NOT EXISTS users_log (
    user_name VARCHAR(255) NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    token TEXT,
    logged_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_user_name (user_name)
);